### ISSUE TITLE
Modify bug

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/InformationModel#126]
Per @kthare10 

I also ran into another issue, when I do a modify where I just add components to the existing VM and don't have any other modifications. I see following exception:
```
Traceback (most recent call last):
    topology_diff = existing_topology.diff(new_topology)
  File "/Users/kthare10/.virtualenvs/ControlFramework1.3/lib/python3.9/site-packages/fim/user/topology.py", line 794, in diff
    ExperimentTopology._exclude_parented_elements(nodes_added, nss_added,
  File "/Users/kthare10/.virtualenvs/ControlFramework1.3/lib/python3.9/site-packages/fim/user/topology.py", line 764, in _exclude_parented_elements
    excluded_components = {c for c in components if ExperimentTopology._is_parented_component(c, nodes)}
  File "/Users/kthare10/.virtualenvs/ControlFramework1.3/lib/python3.9/site-packages/fim/user/topology.py", line 764, in <setcomp>
    excluded_components = {c for c in components if ExperimentTopology._is_parented_component(c, nodes)}
  File "/Users/kthare10/.virtualenvs/ControlFramework1.3/lib/python3.9/site-packages/fim/user/topology.py", line 714, in _is_parented_component
    assert nodes
```

**Comment by ibaldin** [comment]
Addressed in #130
